"""Initial migration

Revision ID: 176188fbf47b
Revises: eb72c5011286
Create Date: 2026-06-25 18:08:02.572677

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "176188fbf47b"
down_revision = "eb72c5011286"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.alter_column(
            "nombre", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    with op.batch_alter_table("hospitals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("estado_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "nombre", existing_type=sa.VARCHAR(length=250), nullable=False
        )
        batch_op.create_foreign_key(
            "fk_hospitals_estado_id", "estados", ["estado_id"], ["id"]
        )
        batch_op.drop_column("estado")

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cedula", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("sexo", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("fecha_ingreso", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("estado_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("hospital_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("area_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("estatus", sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(
            "fk_persons_estado_id", "estados", ["estado_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_persons_hospital_id", "hospitals", ["hospital_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_persons_area_id", "areas", ["area_id"], ["id"])
        batch_op.drop_column("estado")
        batch_op.drop_column("area")
        batch_op.drop_column("hospital_nombre")

    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.alter_column("imported", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("duplicated", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.alter_column("duplicated", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("imported", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hospital_nombre", sa.VARCHAR(length=200), nullable=True)
        )
        batch_op.add_column(sa.Column("area", sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column("estado", sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint("fk_persons_estado_id", type_="foreignkey")
        batch_op.drop_constraint("fk_persons_hospital_id", type_="foreignkey")
        batch_op.drop_constraint("fk_persons_area_id", type_="foreignkey")
        batch_op.drop_column("estatus")
        batch_op.drop_column("area_id")
        batch_op.drop_column("hospital_id")
        batch_op.drop_column("estado_id")
        batch_op.drop_column("fecha_ingreso")
        batch_op.drop_column("sexo")
        batch_op.drop_column("cedula")

    with op.batch_alter_table("hospitals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("estado", sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint("fk_hospitals_estado_id", type_="foreignkey")
        batch_op.alter_column(
            "nombre", existing_type=sa.VARCHAR(length=250), nullable=True
        )
        batch_op.drop_column("estado_id")

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.alter_column(
            "nombre", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    op.drop_table("estados")
    # ### end Alembic commands ###
