"""add nombre apellido to users

Revision ID: 20624c2be387
Revises: 176188fbf47b
Create Date: 2026-06-25 19:44:51.083855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20624c2be387'
down_revision = '176188fbf47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
