"""add estatus model and lowercase normalization

Revision ID: 7d5136331819
Revises: 20624c2be387
Create Date: 2026-06-25 19:54:23.937974

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d5136331819"
down_revision = "20624c2be387"
branch_labels = None
depends_on = None


from sqlalchemy import text


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estatuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    # ### end Alembic commands ###

    conn = op.get_bind()

    # Seed default estatuses
    defaults = ["Hospitalizado", "Trasladado", "Alta", "Fallecido", "No localizado"]
    for s in defaults:
        conn.execute(
            text("INSERT OR IGNORE INTO estatuses (nombre) VALUES (:n)"),
            {"n": s.lower()},
        )

    # Lowercase existing hospital names (handle duplicates by appending a suffix)
    rows = conn.execute(text("SELECT id, nombre FROM hospitals ORDER BY id")).fetchall()
    seen = {}
    for row_id, name in rows:
        if not name:
            continue
        lower = name.strip().lower()
        if lower not in seen:
            seen[lower] = 1
            conn.execute(
                text("UPDATE hospitals SET nombre = :lower WHERE id = :rid"),
                {"lower": lower, "rid": row_id},
            )
        else:
            # Duplicate after lowercasing — append a number
            seen[lower] += 1
            deduped = f"{lower}-{seen[lower]}"
            conn.execute(
                text("UPDATE hospitals SET nombre = :deduped WHERE id = :rid"),
                {"deduped": deduped, "rid": row_id},
            )

    # Lowercase existing area names (same dedup logic)
    rows = conn.execute(text("SELECT id, nombre FROM areas ORDER BY id")).fetchall()
    seen = {}
    for row_id, name in rows:
        if not name:
            continue
        lower = name.strip().lower()
        if lower not in seen:
            seen[lower] = 1
            conn.execute(
                text("UPDATE areas SET nombre = :lower WHERE id = :rid"),
                {"lower": lower, "rid": row_id},
            )
        else:
            seen[lower] += 1
            deduped = f"{lower}-{seen[lower]}"
            conn.execute(
                text("UPDATE areas SET nombre = :deduped WHERE id = :rid"),
                {"deduped": deduped, "rid": row_id},
            )

    # Lowercase existing person estatus values
    conn.execute(
        text(
            "UPDATE persons SET estatus = LOWER(TRIM(estatus)) WHERE estatus IS NOT NULL"
        )
    )


def downgrade():
    op.drop_table("estatuses")
    # NOTE: we do NOT revert existing data to uppercase in downgrade
