"""Inicial2

Revision ID: eb72c5011286
Revises: 
Create Date: 2026-06-25 17:17:22.450439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb72c5011286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('hospital_nombre', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('estado_salud', sa.Text(), nullable=True),
    sa.Column('tiene_familiar', sa.Boolean(), nullable=True),
    sa.Column('nombre_familiar', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('sheet_row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_row')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=True),
    sa.Column('duplicated', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sync_logs')
    op.drop_table('persons')
    op.drop_table('hospitals')
    op.drop_table('areas')
    # ### end Alembic commands ###
